### ISSUE TITLE
Medio remoto via localhost para controlar la reproduccion

### ISSUE THREAD

**Issue by MakuSensei** [brai4u/FlowCast#2]
Hola de nuevo xD quería comentarte algo que se me ocurrió. como en mi caso tengo lejos de la tv mi laptop al cual tengo mis vídeos.
Estaría bueno un medio remoto simple y apto para cualquier dispositivo, por eso la idea que te doy es por medio de localhost y un determinado puerto, poder entrar desde el navegador de un movil o tablet (en mi caso) y darle play desde ahí, si necesitas a alguien que te ayude para pruebas te puedo dar una mano :p menos en lo que sea de programación que no se nada xD apenas manejo simples comandos en linux :v

**Comment by brai4u** [comment]
Cuando tire la nueva actualización, si tenes google home instalado en la tablet lo vas a poder controlar desde ahi, tengo que hacerle algunas pruebas mas
